spring:
  application:
    name: spring-batch-test
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/batch
    # 스키마 위치 설정
    # 다른 데이터베이스를 사용한다면 org.springframework.batch.core 위치에서
    # 알맞는 데이터베이스의 스키마 파일을 사용한다.
#    schema: classpath:/org/springframework/batch/core/schema-h2.sql
  batch:
    job:
      enabled: false # CommandLineRunner 설정 해제
      # CommandLineRunner는 어플리케이션 구동 시점에 특정 작업이 실행될 수 있도록 해주는 역할을 한다.
      # 스케쥴러로 사용할 것이기 때문에 구동 시점에 동작하는 작업을 제거한다.
