spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/batch
      username: sa
      password:
      driver-class-name: org.h2.Driver
      # 스키마 위치 설정
      # 다른 데이터베이스를 사용한다면 org.springframework.batch.core 위치에서
      # 알맞는 데이터베이스의 스키마 파일을 사용한다.
  batch:
    job:
      enabled: false # CommandLineRunner 설정 해제
      # CommandLineRunner는 어플리케이션 구동 시점에 특정 작업이 실행될 수 있도록 해주는 역할을 한다.
      # 스케쥴러로 사용할 것이기 때문에 구동 시점에 동작하는 작업을 제거한다.
---

spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3307/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC
      username: citizen
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      enabled: false